package com.jstorrent.app.debug

import java.net.URLEncoder

/**
 * Helper for adding test torrents in debug builds.
 *
 * These are generated by the Python seeder (packages/engine/integration/python/seed_for_test.py)
 * using a fixed seed (0xDEADBEEF) which produces deterministic data and consistent info hashes.
 */
object TestTorrentHelper {
    /**
     * Info hash for 1GB test file (testdata_1gb.bin).
     * Generated with 1MB piece size and seed 0xDEADBEEF.
     */
    private const val INFO_HASH_1GB = "18a7aacab6d2bc518e336921ccd4b6cc32a9624b"
    private const val DISPLAY_NAME_1GB = "testdata_1gb.bin"

    /**
     * Default seeder port (matches seed_for_test.py default).
     */
    private const val DEFAULT_PORT = 6881

    /**
     * Kitchen sink peer hint hosts - covers all common test environments:
     * - 10.0.2.2: Android emulator → host loopback
     * - 127.0.0.1: localhost (ADB reverse port forwarding)
     * - 100.115.92.206: Crostini container IP on ChromeOS
     * - 192.168.1.131: Dev machine LAN IP (for real device testing)
     */
    private val KITCHEN_SINK_HOSTS = listOf(
        "10.0.2.2",       // Emulator → host
        "127.0.0.1",      // Localhost (ADB reverse)
        "100.115.92.206", // Crostini on ChromeOS
        "192.168.1.131"   // Dev machine LAN IP
    )

    /**
     * Build a magnet link for the 1GB test file with kitchen sink peer hints.
     *
     * This includes peer hints for all common test environments so the torrent
     * will connect to the seeder regardless of how the device is connected.
     *
     * @param port The seeder port (default: 6881)
     * @return A magnet link with multiple x.pe peer hints
     */
    fun buildKitchenSinkMagnet(port: Int = DEFAULT_PORT): String {
        val encodedName = URLEncoder.encode(DISPLAY_NAME_1GB, "UTF-8")
        val peerHints = KITCHEN_SINK_HOSTS.joinToString("&") { host ->
            "x.pe=$host:$port"
        }
        return "magnet:?xt=urn:btih:$INFO_HASH_1GB&dn=$encodedName&$peerHints"
    }
}
