package com.jstorrent.app.e2e

import java.net.URLEncoder

/**
 * Known test magnet links for E2E tests.
 *
 * These are generated by the Python seeder (packages/engine/integration/python/seed_for_test.py)
 * using a fixed seed (0xDEADBEEF) which produces deterministic data and consistent info hashes.
 *
 * To regenerate test data:
 *   cd packages/engine/integration/python
 *   uv run python seed_for_test.py --size 100mb --quiet
 */
object TestMagnets {
    /**
     * Known info hashes for deterministic test data.
     * These are generated using seed 0xDEADBEEF.
     */
    object InfoHashes {
        /**
         * Info hash for 100MB test file (testdata_100mb.bin).
         * Generated with 256KB piece size.
         */
        const val TEST_100MB = "67d01ece1b99c49c257baada0f760b770a7530b9"

        /**
         * Info hash for 1GB test file (testdata_1gb.bin).
         * Generated with 1MB piece size.
         */
        const val TEST_1GB = "18a7aacab6d2bc518e336921ccd4b6cc32a9624b"
    }

    /**
     * Display names for test files.
     */
    object DisplayNames {
        const val TEST_100MB = "testdata_100mb.bin"
        const val TEST_1GB = "testdata_1gb.bin"
    }

    /**
     * Build a magnet link for the 100MB test file with a peer hint.
     *
     * @param host The seeder host IP (e.g., "10.0.2.2" for emulator)
     * @param port The seeder port (default: 6881)
     * @return A magnet link with the x.pe (peer exchange) parameter
     */
    fun buildMagnet100MB(host: String, port: Int): String {
        return buildMagnetLink(
            infoHash = InfoHashes.TEST_100MB,
            displayName = DisplayNames.TEST_100MB,
            peerHost = host,
            peerPort = port
        )
    }

    /**
     * Build a magnet link for the 1GB test file with a peer hint.
     *
     * @param host The seeder host IP (e.g., "10.0.2.2" for emulator)
     * @param port The seeder port (default: 6881)
     * @return A magnet link with the x.pe (peer exchange) parameter
     */
    fun buildMagnet1GB(host: String, port: Int): String {
        return buildMagnetLink(
            infoHash = InfoHashes.TEST_1GB,
            displayName = DisplayNames.TEST_1GB,
            peerHost = host,
            peerPort = port
        )
    }

    /**
     * Build a magnet link with optional peer hint.
     *
     * @param infoHash The torrent info hash (40-char hex string)
     * @param displayName The display name for the torrent
     * @param peerHost Optional peer hint host
     * @param peerPort Optional peer hint port
     * @return A properly formatted magnet link
     */
    fun buildMagnetLink(
        infoHash: String,
        displayName: String,
        peerHost: String? = null,
        peerPort: Int? = null
    ): String {
        val encodedName = URLEncoder.encode(displayName, "UTF-8")
        val base = "magnet:?xt=urn:btih:$infoHash&dn=$encodedName"

        return if (peerHost != null && peerPort != null) {
            "$base&x.pe=$peerHost:$peerPort"
        } else {
            base
        }
    }

    /**
     * Get a magnet link using E2E test configuration.
     *
     * @param arguments Instrumentation arguments for overriding host/port
     * @param size Which size test file to use ("100mb" or "1gb")
     * @return A magnet link configured for the test environment
     */
    fun getMagnetForTest(arguments: android.os.Bundle, size: String = "100mb"): String {
        val host = E2ETestConfig.getSeederHost(arguments)
        val port = E2ETestConfig.getSeederPort(arguments)

        return when (size.lowercase()) {
            "100mb" -> buildMagnet100MB(host, port)
            "1gb" -> buildMagnet1GB(host, port)
            else -> throw IllegalArgumentException("Unknown size: $size. Use '100mb' or '1gb'.")
        }
    }

    /**
     * Get the expected info hash for a given size.
     */
    fun getInfoHashForSize(size: String): String {
        return when (size.lowercase()) {
            "100mb" -> InfoHashes.TEST_100MB
            "1gb" -> InfoHashes.TEST_1GB
            else -> throw IllegalArgumentException("Unknown size: $size. Use '100mb' or '1gb'.")
        }
    }
}
