/**
 * Test magnet links for dev mode.
 *
 * These match the test torrents in android/app/src/main/java/com/jstorrent/app/debug/TestTorrentHelper.kt
 */

/**
 * Kitchen sink peer hint hosts - covers all common test environments:
 * - 10.0.2.2: Android emulator → host loopback
 * - 127.0.0.1: localhost (ADB reverse port forwarding)
 * - 100.115.92.206: Crostini container IP on ChromeOS
 * - 192.168.1.107: Dev machine LAN IP
 * - 192.168.1.131: Dev machine LAN IP (alternate)
 * - 192.168.1.139: Dev machine LAN IP (alternate)
 */
const KITCHEN_SINK_HOSTS = [
  '10.0.2.2',
  '127.0.0.1',
  '100.115.92.206',
  '192.168.1.107',
  '192.168.1.131',
  '192.168.1.139',
]

const DEFAULT_PORT = 6881

function buildPeerHints(port: number = DEFAULT_PORT): string {
  return KITCHEN_SINK_HOSTS.map((host) => `x.pe=${host}:${port}`).join('&')
}

/**
 * 100MB test file - generated by seed_for_test.py with seed 0xDEADBEEF.
 */
export const TEST_100MB_MAGNET = `magnet:?xt=urn:btih:67d01ece1b99c49c257baada0f760b770a7530b9&dn=testdata_100mb.bin&${buildPeerHints()}`

/**
 * 1GB test file - generated by seed_for_test.py with seed 0xDEADBEEF.
 */
export const TEST_1GB_MAGNET = `magnet:?xt=urn:btih:18a7aacab6d2bc518e336921ccd4b6cc32a9624b&dn=testdata_1gb.bin&${buildPeerHints()}`

/**
 * Ubuntu 24.04.3 Server ISO - real-world torrent for testing with public swarm.
 */
export const UBUNTU_SERVER_MAGNET =
  'magnet:?xt=urn:btih:a1dfefec1a9dd7fa8a041ebeeea271db55126d2f' +
  '&dn=ubuntu-24.04.3-live-server-amd64.iso' +
  '&tr=https%3A%2F%2Ftorrent.ubuntu.com%2Fannounce' +
  '&tr=https%3A%2F%2Fipv6.torrent.ubuntu.com%2Fannounce'

/**
 * Big Buck Bunny - public domain video with reliable UDP and WebSocket trackers.
 */
export const BIG_BUCK_BUNNY_MAGNET =
  'magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c' +
  '&dn=Big+Buck+Bunny' +
  '&tr=udp%3A%2F%2Fexplodie.org%3A6969' +
  '&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969' +
  '&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337' +
  '&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969' +
  '&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337' +
  '&tr=wss%3A%2F%2Ftracker.btorrent.xyz' +
  '&tr=wss%3A%2F%2Ftracker.fastcast.nz' +
  '&tr=wss%3A%2F%2Ftracker.openwebtorrent.com' +
  '&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F' +
  '&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent'
